name: Mi Primer Pipeline

on:
  push:
    branches: [ main ] # Se activa cada vez que subes algo a la rama main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Construir imagen de Docker
        run: docker build -t mi-app-devops .

      - name: Simular Test
        run: echo "Ejecutando tests automáticos... ¡Todo OK!"